/**
 * THE SITE MUST NOT CLAIM A COVERAGE NUMBER THAT IS NOT TRUE.
 *
 * 10 Sep 2026: itsnum.com said "77 destinations in 38 countries" in 149
 * places — the footer of every page, the home hero, the schema.org
 * Organization description, llms.txt, and all eleven /agents/ pages. The
 * database had 104 live destinations and had done for some time. Only
 * /destinations/ had been updated, so the same site said both 77 and 104,
 * and the page listing the cities disagreed with the footer beneath it.
 *
 * Two separate harms, and the second is the one that matters:
 *   1. NUM was underselling itself by 27 cities everywhere.
 *   2. A brand whose whole position is "verified, real, checked" was
 *      publishing a number anyone could count and find wrong.
 *
 * The number was hand-typed into 30+ static files, so it was always going to
 * go stale — city 105 would have broken it again. This is the guard: the
 * truth lives in scripts/destinations.mjs (the list that seeds the database),
 * and every coverage claim on the site is checked against it.
 *
 * If this fails after adding a destination, that is the guard working. Update
 * the copy; do not soften the check.
 */
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { DESTINATIONS } from './destinations.mjs';

export const TRUTH = {
  destinations: DESTINATIONS.length,
  countries: new Set(DESTINATIONS.map((d) => d.country)).size,
};

/**
 * llms.txt and llms-full.txt are GENERATED by scripts/seo_files.py, which now
 * derives its numbers from the same destination list. They are still scanned
 * here — a generator can be bypassed by hand-editing the output, and these two
 * files are the ones answer engines read.
 */

/**
 * The claim shapes that are COVERAGE claims, and only those.
 *
 * The first version of this matched any number touching the word
 * "destinations", which flagged two sentences that were perfectly true:
 * "32 destinations have a page of their own" (how many have a dedicated page)
 * and "The remaining 100 destinations are listed at ..." (a subtotal).
 * A guard that cries wolf on correct copy gets switched off, so it only
 * matches the phrasings that assert total coverage.
 */
export const CLAIMS = [
  { re: /\b(?:in|across|all|covers)\s+([\d,]+)\s+(?:destinations|cities)\b/gi, key: 'destinations' },
  { re: /\b([\d,]+)\s+(?:destinations|cities)\s+(?:in|across)\s+[\d,]+\s+countries/gi, key: 'destinations' },
  { re: /\b(?:in|across)\s+([\d,]+)\s+countries\b/gi, key: 'countries' },
  { re: /\bCoverage:\s*[\d,]+\s+places,\s*([\d,]+)\s+destinations/gi, key: 'destinations' },
];

const walk = (dir, out = []) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (/\.(html|txt|md)$/i.test(name)) out.push(p);
  }
  return out;
};

/**
 * Find claims that disagree with the truth.
 *
 * A number is only judged when it is attached to one of the words above —
 * "104 destinations" is a claim, "$104" and "104 Main St" are not.
 */
export function drift(root = 'public') {
  const bad = [];
  for (const file of walk(root)) {
    const text = readFileSync(file, 'utf8');
    for (const { re, key } of CLAIMS) {
      for (const m of text.matchAll(new RegExp(re.source, re.flags))) {
        const n = Number(String(m[1]).replace(/,/g, ''));
        if (!Number.isFinite(n) || n !== TRUTH[key]) {
          bad.push({ file, said: m[0].trim(), should_be: `${TRUTH[key]} ${key === 'countries' ? 'countries' : 'destinations/cities'}` });
        }
      }
    }
  }
  return bad;
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  const bad = drift();
  if (!bad.length) {
    console.log(`[coverage] ok — ${TRUTH.destinations} destinations, ${TRUTH.countries} countries, site agrees`);
  } else {
    console.error(`[coverage] ${bad.length} claim(s) disagree with the destination list:`);
    for (const b of bad.slice(0, 20)) console.error(`  ${b.file}: "${b.said}" — should be ${b.should_be}`);
    process.exit(1);
  }
}
