/* ═══════════════════════════════════════════════════════════════════════════
   venue_pay.js — paylink QR codes: scan at the table, pay the venue directly.

   What this is NOT, by design: a payment processor. NUM never holds, routes,
   or touches money. A paylink QR resolves to /p/<token>, a page that shows
   who you are paying and hands you to the venue's OWN rails — either a
   payment URL they already have (Stripe / PayPal / Square / SumUp link) or
   their own Thai PromptPay identity rendered as a standard EMV QR their
   guest's banking app understands. The venue's money goes to the venue.

   What NUM adds is the part processors don't do: per-table identity
   ("Table 4", "Bar seat 9"), print-ready cards, scan tracking a business can
   read, retirement the moment a card walks off, and the same security sweep
   that watches the check-in system. Scans are METERED (num_pay_events, one
   billable per guest per link per 30 minutes) — but no rate exists and no
   invoice is generated anywhere in this file. Metering is not billing.

   Fraud model this is built against, because it is the attack that actually
   happens to table QR payments: someone re-points a table's code at their own
   account. Three answers here:
     1 · targets are immutable — there is NO edit endpoint. Changing where a
         paylink pays means retiring it and creating a new one, both of which
         are key-gated and logged in num_key_events.
     2 · the pay page names the venue in large type before any pay control:
         a guest sitting in Morrisons Lounge looking at "Pay The Longtail
         Bar" is a guest who stops.
     3 · the sweep watches for scan bursts, unknown-token enumeration, and
         traffic still arriving on retired links.
   ═══════════════════════════════════════════════════════════════════════════ */

/* ── QR encoder, version 6 / ECC level M ─────────────────────────────────────
   A second fixed-shape encoder, deliberately SEPARATE from the proven v4-H
   closure that draws /v/ check-in codes — sharing nothing means a change here
   can never bend a symbol that is already printed on a thousand table cards.

   Why a second shape at all: an EMV PromptPay payload runs 70–90 characters,
   and v4-H tops out at 34. Version 6 at level M holds 106 — headroom for
   e-wallet ids plus a fixed amount — and M (~15% recovery) is the level the
   EMV merchant-presented spec itself recommends for payment QRs.

   Correctness is demonstrated, not asserted: qr6.verify.mjs diffs this
   encoder's module matrix cell-for-cell against the python `qrcode` reference
   for hundreds of random EMV-shaped payloads, then decodes the rendered
   artwork with OpenCV, then round-trips real PromptPay payloads generated by
   the python `promptpay` package. All three must pass before deploy.        */
const qr6m = (function () {
  const SIZE = 41;                 // version 6: 17 + 6·4
  const DATA_CW = 108;             // 4 blocks × 27
  const BLOCKS = 4, BLOCK_DATA = 27, BLOCK_EC = 16;   // RS(43,27) × 4 = 172
  const EC_LEVEL_BITS = 0b00;      // M, as it appears in the format string

  const EXP = new Uint8Array(512), LOG = new Uint8Array(256);
  (function () {
    let x = 1;
    for (let i = 0; i < 255; i++) { EXP[i] = x; LOG[x] = i; x <<= 1; if (x & 0x100) x ^= 0x11d; }
    for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255];
  })();
  const mul = (a, b) => (a === 0 || b === 0 ? 0 : EXP[LOG[a] + LOG[b]]);

  function genPoly(n) {
    let p = [1];
    for (let i = 0; i < n; i++) {
      const q = [1, EXP[i]], r = new Array(p.length + 1).fill(0);
      for (let a = 0; a < p.length; a++) for (let b = 0; b < 2; b++) r[a + b] ^= mul(p[a], q[b]);
      p = r;
    }
    return p;
  }
  function ecFor(data, n) {
    const g = genPoly(n), res = new Array(data.length + n).fill(0);
    data.forEach((v, i) => (res[i] = v));
    for (let i = 0; i < data.length; i++) {
      const f = res[i];
      if (f === 0) continue;
      for (let j = 0; j < g.length; j++) res[i + j] ^= mul(g[j], f);
    }
    return res.slice(data.length);
  }

  function encodeData(text) {
    const bytes = new TextEncoder().encode(text);
    if (bytes.length > DATA_CW - 2) throw new Error(`payload too long for v6-M: ${bytes.length} bytes`);
    const bits = [];
    const push = (v, n) => { for (let i = n - 1; i >= 0; i--) bits.push((v >> i) & 1); };
    push(0b0100, 4);               // byte mode
    push(bytes.length, 8);         // v1–9: 8-bit length
    bytes.forEach((b) => push(b, 8));
    const cap = DATA_CW * 8;
    push(0, Math.min(4, cap - bits.length));
    while (bits.length % 8) bits.push(0);
    const cw = [];
    for (let i = 0; i < bits.length; i += 8) cw.push(bits.slice(i, i + 8).reduce((a, b) => (a << 1) | b, 0));
    const PAD = [0xec, 0x11];
    for (let i = 0; cw.length < DATA_CW; i++) cw.push(PAD[i % 2]);
    return cw;
  }

  function finalCodewords(text) {
    const cw = encodeData(text);
    const dB = [], eB = [];
    for (let i = 0; i < BLOCKS; i++) {
      const d = cw.slice(i * BLOCK_DATA, (i + 1) * BLOCK_DATA);
      dB.push(d); eB.push(ecFor(d, BLOCK_EC));
    }
    const out = [];
    for (let i = 0; i < BLOCK_DATA; i++) for (const b of dB) out.push(b[i]);
    for (let i = 0; i < BLOCK_EC; i++) for (const b of eB) out.push(b[i]);
    return out;
  }

  const newMatrix = () => Array.from({ length: SIZE }, () => new Array(SIZE).fill(null));

  function placeFunctionPatterns(m) {
    const finder = (r, c) => {
      for (let i = -1; i <= 7; i++) for (let j = -1; j <= 7; j++) {
        const rr = r + i, cc = c + j;
        if (rr < 0 || rr >= SIZE || cc < 0 || cc >= SIZE) continue;
        const on = (i >= 0 && i <= 6 && (j === 0 || j === 6)) ||
                   (j >= 0 && j <= 6 && (i === 0 || i === 6)) ||
                   (i >= 2 && i <= 4 && j >= 2 && j <= 4);
        m[rr][cc] = on ? 1 : 0;
      }
    };
    finder(0, 0); finder(0, SIZE - 7); finder(SIZE - 7, 0);
    for (let i = 8; i < SIZE - 8; i++) {
      const v = i % 2 === 0 ? 1 : 0;
      if (m[6][i] === null) m[6][i] = v;
      if (m[i][6] === null) m[i][6] = v;
    }
    // version 6 has one alignment pattern clear of the finders, centred (34,34)
    const ac = 34;
    for (let i = -2; i <= 2; i++) for (let j = -2; j <= 2; j++) {
      m[ac + i][ac + j] = (Math.max(Math.abs(i), Math.abs(j)) !== 1) ? 1 : 0;
    }
    m[SIZE - 8][8] = 1;            // always-dark module (4·V+9, 8)
  }

  const FORMAT_MASK = 0b101010000010010;
  function formatBits(mask) {
    const data = (EC_LEVEL_BITS << 3) | mask;
    let v = data << 10;
    for (let i = 14; i >= 10; i--) if ((v >> i) & 1) v ^= 0b10100110111 << (i - 10);
    return ((data << 10) | v) ^ FORMAT_MASK;
  }
  function placeFormat(m, mask) {
    const f = formatBits(mask);
    const bit = (i) => (f >> (14 - i)) & 1;     // MSB-first, as the spec walks it
    for (let i = 0; i <= 5; i++) m[8][i] = bit(i);
    m[8][7] = bit(6); m[8][8] = bit(7); m[7][8] = bit(8);
    for (let i = 9; i <= 14; i++) m[14 - i][8] = bit(i);
    for (let i = 0; i <= 6; i++) m[SIZE - 1 - i][8] = bit(i);          // 7 vertical
    for (let i = 7; i <= 14; i++) m[8][SIZE - 15 + i] = bit(i);        // 8 horizontal
  }

  const MASKS = [
    (r, c) => (r + c) % 2 === 0,
    (r) => r % 2 === 0,
    (_, c) => c % 3 === 0,
    (r, c) => (r + c) % 3 === 0,
    (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
    (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
    (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
    (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0,
  ];

  function placeData(m, cw, mask) {
    let bitIdx = 0;
    const total = cw.length * 8;
    let up = true;
    for (let right = SIZE - 1; right > 0; right -= 2) {
      if (right === 6) right--;
      for (let k = 0; k < SIZE; k++) {
        const r = up ? SIZE - 1 - k : k;
        for (const c of [right, right - 1]) {
          if (m[r][c] !== null) continue;
          let v = 0;
          if (bitIdx < total) v = (cw[bitIdx >> 3] >> (7 - (bitIdx & 7))) & 1;
          bitIdx++;
          m[r][c] = MASKS[mask](r, c) ? v ^ 1 : v;
        }
      }
      up = !up;
    }
  }

  /* Mask scoring — a faithful port of python-qrcode's `lost_point`, INCLUDING
     its skip-optimizations in levels 2 and 3 (which make its scores deviate
     slightly from a literal reading of the ISO rules). That is deliberate:
     matching the reference's scorer means our chosen mask — and therefore the
     entire symbol — is bit-identical to what the world's most widely deployed
     generator would print, a population of symbols that has been decoded by
     real phone cameras at enormous scale. qr6.verify.mjs asserts the
     identity; a "better" scorer that ships an untested symbol is worse. */
  function penalty(m) {
    let p = 0;
    // level 1 — runs of 5+ in rows and columns: (len - 2) each
    const runs = (get) => {
      for (let a = 0; a < SIZE; a++) {
        let prev = get(a, 0), len = 0;
        for (let b = 0; b < SIZE; b++) {
          if (get(a, b) === prev) len++;
          else { if (len >= 5) p += len - 2; len = 1; prev = get(a, b); }
        }
        if (len >= 5) p += len - 2;
      }
    };
    runs((a, b) => m[a][b]); runs((a, b) => m[b][a]);
    // level 2 — 2×2 blocks, with the reference's next()-skip semantics
    for (let row = 0; row < SIZE - 1; row++) {
      for (let col = 0; col < SIZE - 1; col++) {
        const tr = m[row][col + 1];
        if (tr !== m[row + 1][col + 1]) { col++; continue; }
        if (tr !== m[row][col]) continue;
        if (tr !== m[row + 1][col]) continue;
        p += 3;
      }
    }
    // level 3 — 1:1:3:1:1 finder-like pattern with 4-light flank, with the
    // reference's horspool skip (advance an extra cell when cell+10 is dark)
    const l3 = (get) => {
      for (let a = 0; a < SIZE; a++) {
        for (let b = 0; b < SIZE - 10; b++) {
          if (!get(a, b + 1) && get(a, b + 4) && !get(a, b + 5) && get(a, b + 6) && !get(a, b + 9) &&
              ((get(a, b) && get(a, b + 2) && get(a, b + 3) &&
                !get(a, b + 7) && !get(a, b + 8) && !get(a, b + 10)) ||
               (!get(a, b) && !get(a, b + 2) && !get(a, b + 3) &&
                get(a, b + 7) && get(a, b + 8) && get(a, b + 10)))) p += 40;
          if (get(a, b + 10)) b++;
        }
      }
    };
    l3((a, b) => m[a][b]); l3((a, b) => m[b][a]);
    // level 4 — dark-proportion departure from 50%, float division as reference
    let dark = 0;
    for (let r = 0; r < SIZE; r++) for (let c = 0; c < SIZE; c++) dark += m[r][c];
    p += Math.trunc(Math.abs((dark / (SIZE * SIZE)) * 100 - 50) / 5) * 10;
    return p;
  }

  function matrixWithMask(text, mask) {
    const m = newMatrix();
    placeFunctionPatterns(m);
    placeFormat(m, mask);
    placeData(m, finalCodewords(text), mask);
    return m;
  }

  /* The reference scores each candidate mask on a TEST-MODE matrix: format
     info and the always-dark module blanked to light (makeImpl(test=True)).
     Scoring the real matrix instead picks a different mask often enough to
     ship symbols the reference would never print — so we blank the same 31
     cells before scoring, and only the winning mask gets real format bits. */
  function blankFormatCells(m) {
    for (let i = 0; i <= 8; i++) { if (i !== 6) { m[8][i] = 0; m[i][8] = 0; } }
    for (let i = 0; i <= 6; i++) m[SIZE - 1 - i][8] = 0;
    for (let i = 7; i <= 14; i++) m[8][SIZE - 15 + i] = 0;
    m[SIZE - 8][8] = 0;
    return m;
  }

  function matrix(text) {
    let bestMask = 0, bestScore = Infinity;
    for (let mask = 0; mask < 8; mask++) {
      const s = penalty(blankFormatCells(matrixWithMask(text, mask)));
      if (s < bestScore) { bestScore = s; bestMask = mask; }
    }
    return matrixWithMask(text, bestMask);
  }

  function svg(text, { border = 3, dark = "#131a16", light = "#ffffff" } = {}) {
    const m = matrix(text);
    const n = SIZE + border * 2, d = [];
    for (let r = 0; r < SIZE; r++) {
      let c = 0;
      while (c < SIZE) {
        if (m[r][c]) {
          let e = c;
          while (e + 1 < SIZE && m[r][e + 1]) e++;
          d.push(`M${c + border} ${r + border}h${e - c + 1}v1h-${e - c + 1}z`);
          c = e + 1;
        } else c++;
      }
    }
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${n} ${n}" ` +
      `shape-rendering="crispEdges" role="img" aria-label="PromptPay QR code">` +
      `<rect width="${n}" height="${n}" fill="${light}"/>` +
      `<path fill="${dark}" d="${d.join("")}"/></svg>`;
  }

  return { matrix, matrixWithMask, svg, SIZE };
})();

/* ── PromptPay EMV payload ───────────────────────────────────────────────────
   EMVCo merchant-presented TLV, byte-for-byte the format the python
   `promptpay` reference produces (verified in qr6.verify.mjs):
     000201 · 010211(static)/010212(has amount) · 29xx merchant-account
     [0016 A000000677010111 + proxy] · 5802TH · 5303764 · [54xx amount] ·
     6304 + CRC-16/CCITT-FALSE, uppercase.
   Proxy forms: phone 0812345678 → 0066812345678 (13) · tax id: 13 digits
   as given · e-wallet: 15 digits as given.                                  */
function promptPayProxy(idRaw) {
  const id = String(idRaw || "").replace(/[^0-9]/g, "");
  if (/^0\d{9}$/.test(id)) return { kind: "phone",   proxy: "0066" + id.slice(1), sub: "01" };
  if (/^\d{13}$/.test(id)) return { kind: "tax_id",  proxy: id,                   sub: "02" };
  if (/^\d{15}$/.test(id)) return { kind: "ewallet", proxy: id,                   sub: "03" };
  return null;
}

function crc16ccitt(s) {
  let crc = 0xffff;
  for (let i = 0; i < s.length; i++) {
    crc ^= s.charCodeAt(i) << 8;
    for (let b = 0; b < 8; b++) crc = crc & 0x8000 ? ((crc << 1) ^ 0x1021) & 0xffff : (crc << 1) & 0xffff;
  }
  return crc.toString(16).toUpperCase().padStart(4, "0");
}

const tlv = (tag, value) => tag + String(value.length).padStart(2, "0") + value;

function promptPayPayload(idRaw, amount) {
  const p = promptPayProxy(idRaw);
  if (!p) return null;
  const merchant = tlv("29", tlv("00", "A000000677010111") + tlv(p.sub, p.proxy));
  let s = tlv("00", "01") + tlv("01", amount ? "12" : "11") + merchant +
          tlv("58", "TH") + tlv("53", "764");
  if (amount) s += tlv("54", Number(amount).toFixed(2));
  s += "6304";
  return s + crc16ccitt(s);
}

/* ── validation ──────────────────────────────────────────────────────────────
   A paylink target is the one field where bad input becomes someone else's
   lost money, so the rules are strict and the refusals are specific.        */
function validPayTarget(kind, raw) {
  if (kind === "promptpay") {
    const p = promptPayProxy(raw);
    if (!p) return { ok: false, error: "bad_promptpay_id",
      hint: "a Thai mobile (0812345678), 13-digit tax ID, or 15-digit e-wallet ID" };
    return { ok: true, target: String(raw).replace(/[^0-9]/g, ""), promptpay_kind: p.kind };
  }
  if (kind === "url") {
    const s = String(raw || "").trim();
    if (s.length > 300) return { ok: false, error: "url_too_long" };
    let u;
    try { u = new URL(s); } catch (e) { return { ok: false, error: "bad_url" }; }
    if (u.protocol !== "https:") return { ok: false, error: "https_only" };
    if (u.username || u.password) return { ok: false, error: "no_credentials_in_url" };
    if (/^(\d{1,3}\.){3}\d{1,3}$/.test(u.hostname) || u.hostname.includes("["))
      return { ok: false, error: "no_ip_hosts" };
    const h = u.hostname.toLowerCase();
    if (h === "itsnum.com" || h.endsWith(".itsnum.com"))
      return { ok: false, error: "target_cannot_be_num" };
    return { ok: true, target: u.href };
  }
  return { ok: false, error: "bad_kind", kinds: ["url", "promptpay"] };
}

function validPayAmount(raw) {
  if (raw == null || raw === "") return { ok: true, amount: null };
  const n = Number(raw);
  if (!isFinite(n) || n <= 0 || n > 1000000) return { ok: false, error: "bad_amount" };
  return { ok: true, amount: n.toFixed(2) };
}

const PAY_CURRENCIES = ["THB", "GBP", "USD", "EUR"];

/* ── event log — the meter ───────────────────────────────────────────────────
   Every event is written; `billable` marks the ones a future invoice could
   count. One billable per guest per link per 30 minutes: a refresh, a
   double-scan, a flaky connection must never become two billed scans.
   Nothing in this codebase turns the meter into a charge — that requires a
   rate, and rates are set by a person, not by code.                         */
async function logPayEvent(env, req, o) {
  try {
    let billable = 0;
    if (o.kind === "scan" && o.active) {
      const vid = await visitorId(req, env);
      const dup = await env.DB.prepare(
        `SELECT 1 FROM num_pay_events
          WHERE token=? AND visitor_id=? AND billable=1
            AND created_at > datetime('now','-30 minutes') LIMIT 1`
      ).bind(o.token, vid).first();
      billable = dup ? 0 : 1;
      o.visitor_id = vid;
    }
    await env.DB.prepare(
      `INSERT INTO num_pay_events (token,business_id,kind,billable,visitor_id,ip_hash,day,created_at)
       VALUES (?,?,?,?,?,?,?,?)`
    ).bind(o.token, o.business_id || "", o.kind, billable, o.visitor_id || null,
           await ipHash(req), now().slice(0, 10), now()).run();
    return billable;
  } catch (e) { console.warn("[pay] log failed:", String(e).slice(0, 120)); return 0; }
}

/* ── GET /p/<token> — what the guest's camera opens ─────────────────────── */
async function payLanding(req, env, tok) {
  const ptok = clean(tok, 40).toUpperCase();
  const link = await env.DB.prepare(
    `SELECT l.token, l.business_id, l.label, l.kind, l.target, l.amount, l.currency,
            l.state, b.name AS business_name
       FROM num_paylinks l JOIN businesses b ON b.id = l.business_id
      WHERE l.token = ?`
  ).bind(ptok).first();

  if (!link) {
    await logPayEvent(env, req, { token: ptok, business_id: "", kind: "unknown_token" });
    return HTML(payPage({ state: "unknown" }), 404);
  }
  if (link.state === "revoked") {
    await logPayEvent(env, req, { token: ptok, business_id: link.business_id, kind: "retired_view" });
    return HTML(payPage({ state: "retired", venue: link.business_name }), 410);
  }
  await logPayEvent(env, req, { token: ptok, business_id: link.business_id, kind: "scan", active: true });
  return HTML(payPage({
    state: "pay", token: ptok, venue: link.business_name, label: link.label,
    kind: link.kind, amount: link.amount, currency: link.currency,
    promptpayId: link.kind === "promptpay" ? link.target : null,
  }));
}

/* ── GET /p/<token>/go — the tracked hop to the venue's own rails ────────── */
async function payGo(req, env, tok) {
  const ptok = clean(tok, 40).toUpperCase();
  const link = await env.DB.prepare(
    "SELECT token,business_id,kind,target,state FROM num_paylinks WHERE token=?"
  ).bind(ptok).first();
  if (!link || link.kind !== "url") return TEXT("not found", 404);
  if (link.state === "revoked") return TEXT("retired", 410);
  await logPayEvent(env, req, { token: ptok, business_id: link.business_id, kind: "tap_through" });
  return new Response(null, { status: 302, headers: { location: link.target, "cache-control": "no-store" } });
}

/* ── QR artwork ──────────────────────────────────────────────────────────────
   /api/pay/qr/<TOKEN>.svg  — the NUM link QR (camera → /p/ page), any kind.
   /api/pay/emv/<TOKEN>.svg — the PromptPay EMV QR (banking app), promptpay
   links only: refusing to draw it for a url-kind link means a print sheet
   can never carry a bank-scannable code that pays nobody.
   Both public by design — they encode what is printed on a card anyone can
   photograph, and nothing else.                                             */
async function payQrRoute(req, env, rest) {
  const t = clean(String(rest || "").replace(/\.svg$/i, ""), 40).toUpperCase();
  if (!/^[A-Z0-9]{4,12}$/.test(t)) return TEXT("bad token", 400);
  const row = await env.DB.prepare("SELECT token FROM num_paylinks WHERE token=?").bind(t).first();
  if (!row) return TEXT("unknown token", 404);
  return new Response(qrSvg((env.SITE || "https://itsnum.com") + "/p/" + t), {
    headers: { "content-type": "image/svg+xml; charset=utf-8",
               "cache-control": "public, max-age=31536000, immutable" } });
}

async function payEmvRoute(req, env, rest) {
  const t = clean(String(rest || "").replace(/\.svg$/i, ""), 40).toUpperCase();
  if (!/^[A-Z0-9]{4,12}$/.test(t)) return TEXT("bad token", 400);
  const row = await env.DB.prepare(
    "SELECT token,kind,target,amount,state FROM num_paylinks WHERE token=?"
  ).bind(t).first();
  if (!row || row.kind !== "promptpay") return TEXT("unknown token", 404);
  if (row.state === "revoked") return TEXT("retired", 410);
  const payload = promptPayPayload(row.target, row.amount);
  if (!payload) return TEXT("bad id", 500);
  return new Response(qr6m.svg(payload), {
    headers: { "content-type": "image/svg+xml; charset=utf-8",
               "cache-control": "public, max-age=86400" } });
}

/* ── manager API (all bizAuth-gated, all logged) ─────────────────────────── */
async function venuePayList(req, env, url) {
  const biz = await bizAuth(env, url, req);
  if (!biz) return J({ ok: false, error: "unauthorised" }, 401);
  const { results } = await env.DB.prepare(
    `SELECT l.token, l.label, l.kind, l.target, l.amount, l.currency, l.zone_type,
            l.state, l.created_at, l.revoked_at,
            (SELECT COUNT(*) FROM num_pay_events e
              WHERE e.token = l.token AND e.kind='scan')        AS scans,
            (SELECT COUNT(*) FROM num_pay_events e
              WHERE e.token = l.token AND e.kind='tap_through') AS taps,
            (SELECT MAX(created_at) FROM num_pay_events e WHERE e.token = l.token) AS last_scan
       FROM num_paylinks l
      WHERE l.business_id = ?
      ORDER BY l.state = 'revoked', l.created_at`
  ).bind(biz.id).all();
  const month = await env.DB.prepare(
    `SELECT COUNT(*) AS n FROM num_pay_events
      WHERE business_id=? AND kind='scan' AND day >= ?`
  ).bind(biz.id, now().slice(0, 8) + "01").first();
  return J({ ok: true, business: biz.name, month_scans: month?.n || 0, paylinks: results || [] });
}

async function venuePayCreate(req, env, url) {
  const biz = await bizAuth(env, url, req);
  if (!biz) return J({ ok: false, error: "unauthorised" }, 401);
  let b;
  try { b = await readJSON(req, 4096); } catch (e) { return J({ ok: false }, 400); }

  const label = clean(b.label, 40);
  if (!label) return J({ ok: false, error: "label_required" }, 400);
  const kind = clean(b.kind, 12);
  const vt = validPayTarget(kind, b.target);
  if (!vt.ok) return J(vt, 400);
  const va = validPayAmount(b.amount);
  if (!va.ok) return J(va, 400);
  const currency = PAY_CURRENCIES.includes(clean(b.currency, 3).toUpperCase())
    ? clean(b.currency, 3).toUpperCase() : "THB";

  const live = await env.DB.prepare(
    "SELECT COUNT(*) AS n FROM num_paylinks WHERE business_id=? AND state='active'"
  ).bind(biz.id).first();
  if ((live?.n || 0) >= MAX_ACTIVE_CODES)
    return J({ ok: false, error: "too_many_paylinks", max: MAX_ACTIVE_CODES }, 409);

  const dup = await env.DB.prepare(
    "SELECT token FROM num_paylinks WHERE business_id=? AND state='active' AND lower(label)=lower(?)"
  ).bind(biz.id, label).first();
  if (dup) return J({ ok: false, error: "label_exists", token: dup.token }, 409);

  for (let attempt = 0; attempt < 6; attempt++) {
    const t = newToken();
    try {
      await env.DB.prepare(
        `INSERT INTO num_paylinks
           (token,business_id,label,kind,target,promptpay_kind,amount_mode,amount,currency,zone_type,state,created_at)
         VALUES (?,?,?,?,?,?,?,?,?,?, 'active', ?)`
      ).bind(t, biz.id, label, kind, vt.target, vt.promptpay_kind || null,
             va.amount ? "fixed" : "open", va.amount, currency,
             clean(b.zone_type, 20) || null, now()).run();
      await logKeyEvent(env, req, biz.id, "ok", "paylink_create:" + label);
      return J({ ok: true, token: t, label, kind,
                 url: (env.SITE || "https://itsnum.com") + "/p/" + t });
    } catch (e) { if (!String(e).includes("UNIQUE")) throw e; }
  }
  return J({ ok: false, error: "could_not_allocate" }, 503);
}

/* Retire / reinstate. There is deliberately no way to CHANGE a target —
   where money goes is immutable per token. Retire it, make a new one. */
async function venuePayState(req, env, url) {
  const biz = await bizAuth(env, url, req);
  if (!biz) return J({ ok: false, error: "unauthorised" }, 401);
  let b;
  try { b = await readJSON(req, 2048); } catch (e) { return J({ ok: false }, 400); }
  const t = clean(b.token, 40).toUpperCase();
  const to = clean(b.state, 12);
  if (!t || !["revoked", "active"].includes(to))
    return J({ ok: false, error: "missing_fields" }, 400);
  const row = await env.DB.prepare(
    "SELECT token,state,label FROM num_paylinks WHERE token=? AND business_id=?"
  ).bind(t, biz.id).first();
  if (!row) return J({ ok: false, error: "unknown_token" }, 404);
  if (row.state === to) return J({ ok: true, unchanged: true, state: to });
  await env.DB.prepare(
    to === "revoked"
      ? "UPDATE num_paylinks SET state='revoked', revoked_at=?, revoked_by=? WHERE token=?"
      : "UPDATE num_paylinks SET state='active', revoked_at=NULL, revoked_by=NULL WHERE token=?"
  ).bind(...(to === "revoked" ? [now(), "biz:" + biz.id, t] : [t])).run();
  await logKeyEvent(env, req, biz.id, "ok", "paylink_" + to + ":" + row.label);
  return J({ ok: true, token: t, state: to, label: row.label });
}

/* Bulk: one payment identity, a whole floor of labelled QRs.
   { template:"bar", kind, target } or { zone_type, count, kind, target }.  */
async function venuePayBulk(req, env, url) {
  const biz = await bizAuth(env, url, req);
  if (!biz) return J({ ok: false, error: "unauthorised" }, 401);
  let b;
  try { b = await readJSON(req, 4096); } catch (e) { return J({ ok: false }, 400); }

  const kind = clean(b.kind, 12);
  const vt = validPayTarget(kind, b.target);
  if (!vt.ok) return J(vt, 400);
  const va = validPayAmount(b.amount);
  if (!va.ok) return J(va, 400);
  const currency = PAY_CURRENCIES.includes(clean(b.currency, 3).toUpperCase())
    ? clean(b.currency, 3).toUpperCase() : "THB";

  let plan = [];
  if (b.template) {
    const tp = FLOOR_TEMPLATES[clean(b.template, 20)];
    if (!tp) return J({ ok: false, error: "unknown_template",
                        templates: Object.keys(FLOOR_TEMPLATES) }, 400);
    for (const [zone, n] of Object.entries(tp.zones))
      for (let i = 1; i <= n; i++)
        plan.push([zone, n === 1 ? ZONE_LABEL[zone] : `${ZONE_LABEL[zone]} ${i}`]);
  } else {
    const zone = clean(b.zone_type, 20);
    const count = Math.min(Math.max(1, Math.round(Number(b.count) || 0)), 100);
    if (!ZONE_TYPES.includes(zone) || !count)
      return J({ ok: false, error: "bad_zone_or_count", zones: ZONE_TYPES }, 400);
    let start = Math.max(1, Math.round(Number(b.start) || 0));
    if (!b.start) {
      const ex = await env.DB.prepare(
        "SELECT COUNT(*) AS n FROM num_paylinks WHERE business_id=? AND zone_type=? AND state='active'"
      ).bind(biz.id, zone).first();
      start = (ex?.n || 0) + 1;
    }
    for (let i = 0; i < count; i++)
      plan.push([zone, count === 1 && start === 1 ? ZONE_LABEL[zone]
                                                  : `${ZONE_LABEL[zone]} ${start + i}`]);
  }

  const live = await env.DB.prepare(
    "SELECT COUNT(*) AS n FROM num_paylinks WHERE business_id=? AND state='active'"
  ).bind(biz.id).first();
  if ((live?.n || 0) + plan.length > MAX_ACTIVE_CODES)
    return J({ ok: false, error: "too_many_paylinks",
               active: live?.n || 0, requested: plan.length, max: MAX_ACTIVE_CODES }, 409);

  const { results: existing } = await env.DB.prepare(
    "SELECT lower(label) AS l FROM num_paylinks WHERE business_id=? AND state='active'"
  ).bind(biz.id).all();
  const have = new Set((existing || []).map((r) => r.l));

  const made = [], skipped = [];
  const site = env.SITE || "https://itsnum.com";
  for (const [zone, label] of plan) {
    if (have.has(label.toLowerCase())) { skipped.push(label); continue; }
    for (let attempt = 0; attempt < 6; attempt++) {
      const t = newToken();
      try {
        await env.DB.prepare(
          `INSERT INTO num_paylinks
             (token,business_id,label,kind,target,promptpay_kind,amount_mode,amount,currency,zone_type,state,created_at)
           VALUES (?,?,?,?,?,?,?,?,?,?, 'active', ?)`
        ).bind(t, biz.id, label, kind, vt.target, vt.promptpay_kind || null,
               va.amount ? "fixed" : "open", va.amount, currency, zone, now()).run();
        made.push({ token: t, label, zone_type: zone, url: `${site}/p/${t}` });
        break;
      } catch (e) { if (!String(e).includes("UNIQUE")) throw e; }
    }
  }
  await logKeyEvent(env, req, biz.id, "ok", "paylink_bulk:" + made.length);
  return J({ ok: true, created: made.length, skipped, paylinks: made });
}

/* ── GET /api/admin/pay/meter (x-admin-key) — the future invoice's source ──
   Read-only rollup of billable scans per business per month. This is the
   ONLY consumer of the `billable` flag, and it charges nobody: it exists so
   that when a rate is finally set, the first invoice is computed from data
   that was being collected honestly all along.                              */
async function adminPayMeter(req, env) {
  const key = req.headers.get("x-admin-key") || "";
  if (!env.ADMIN_KEY || !sameSecret(env.ADMIN_KEY, key))
    return J({ ok: false, error: "unauthorised" }, 401);
  const { results } = await env.DB.prepare(
    `SELECT e.business_id, b.name, substr(e.day,1,7) AS month,
            SUM(e.billable) AS billable_scans,
            SUM(CASE WHEN e.kind='scan' THEN 1 ELSE 0 END) AS raw_scans,
            SUM(CASE WHEN e.kind='tap_through' THEN 1 ELSE 0 END) AS tap_throughs
       FROM num_pay_events e LEFT JOIN businesses b ON b.id = e.business_id
      WHERE e.business_id != ''
      GROUP BY e.business_id, month
      ORDER BY month DESC, billable_scans DESC LIMIT 200`
  ).all();
  return J({ ok: true, note: "meter only — no rate is set and nothing is invoiced",
             months: results || [] });
}

/* ── security sweep additions ────────────────────────────────────────────────
   Returns findings in the same shape securitySweep() stores; called from it.*/
async function payFindings(env) {
  const findings = [];
  const q = async (sql, ...args) =>
    (await env.DB.prepare(sql).bind(...args).all()).results || [];

  // 6 · unknown pay tokens from one network — someone enumerating /p/
  for (const r of await q(
    `SELECT COALESCE(ip_hash,'?') AS net, COUNT(*) AS n
       FROM num_pay_events
      WHERE kind='unknown_token' AND created_at > datetime('now','-1 day')
      GROUP BY ip_hash HAVING n > 30`)) {
    findings.push({ kind: "pay_token_scanning", subject: r.net, severity: "warn",
      evidence: `${r.n} scans of nonexistent paylinks from one network in 24h` });
  }

  // 7 · scan burst on one link — a misprint gone viral, or abuse
  for (const r of await q(
    `SELECT token, business_id, COUNT(*) AS n
       FROM num_pay_events
      WHERE kind='scan' AND created_at > datetime('now','-1 day')
      GROUP BY token HAVING n > 300`)) {
    findings.push({ kind: "pay_scan_burst", subject: r.business_id + "/" + r.token,
      severity: "warn", evidence: `${r.n} scans of one paylink in 24h` });
  }

  // 8 · retired links still being scanned — old cards are still on tables,
  //     which after a fraud-driven retirement is exactly the wrong state
  for (const r of await q(
    `SELECT business_id, COUNT(*) AS n
       FROM num_pay_events
      WHERE kind='retired_view' AND created_at > datetime('now','-1 day')
      GROUP BY business_id HAVING n > 20`)) {
    findings.push({ kind: "pay_retired_traffic", subject: r.business_id, severity: "warn",
      evidence: `${r.n} scans in 24h hit retired paylinks — printed cards likely still out` });
  }
  return findings;
}

/* ── pages ─────────────────────────────────────────────────────────────── */
function payShell(inner, title) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex"><title>${esc(title || "Pay — NUM")}</title>
<style>
body{font:17px/1.6 -apple-system,'Segoe UI',sans-serif;background:#faf8f4;color:#131a16;
  margin:0;display:flex;justify-content:center}
main{max-width:430px;width:100%;padding:28px 22px 40px}
.venue{font-size:24px;font-weight:800;letter-spacing:-.3px;margin:10px 0 2px}
.lbl{display:inline-block;font-size:14px;font-weight:600;background:#fff;
  border:1px solid #e0ddd4;border-radius:8px;padding:2px 10px;margin-left:6px;vertical-align:3px}
h1{font-size:20px;margin:14px 0 6px}
.lede{color:#4a5450;margin:0 0 18px}
.amount{font-size:34px;font-weight:800;margin:8px 0 16px}
.btn{display:block;width:100%;text-align:center;background:#1f3a34;color:#fff;border:0;
  border-radius:12px;padding:16px;font-size:18px;font-weight:700;text-decoration:none;box-sizing:border-box}
.btn.ghost{background:transparent;color:#1f3a34;border:1.5px solid #1f3a34;margin-top:10px}
.ppbox{background:#fff;border:1px solid #e0ddd4;border-radius:14px;padding:18px;margin:14px 0}
.ppid{font-size:22px;font-weight:700;letter-spacing:1px;font-variant-numeric:tabular-nums}
.note{font-size:14px;color:#4a5450;margin-top:18px}
.warn{font-size:14px;background:#fff;border:1px solid #e0ddd4;border-left:4px solid #b4552d;
  border-radius:8px;padding:10px 12px;margin-top:16px;color:#4a5450}
.foot{font-size:13px;color:#7a827e;margin-top:26px}
</style></head><body><main>${inner}</main></body></html>`;
}

function payPage(o) {
  if (o.state === "unknown") return payShell(`
    <h1>This payment code isn't one of ours</h1>
    <p class="lede">Nothing was charged. If this QR was on a table or a bill,
    it did not come from NUM — please pay the venue directly and let staff know.</p>
    <a class="btn ghost" href="https://itsnum.com/">Go to NUM</a>`, "Unknown code — NUM");

  if (o.state === "retired") return payShell(`
    <h1>This payment code has been retired</h1>
    <p class="lede">${esc(o.venue)} replaced it. Ask staff for the current one —
    old codes stop working the moment they're replaced, which is the point.</p>
    <a class="btn ghost" href="https://itsnum.com/">Go to NUM</a>`, "Retired code — NUM");

  const amt = o.amount ? `${esc(o.currency)} ${esc(o.amount)}` : null;
  const inner = o.kind === "url" ? `
    <div class="venue">${esc(o.venue)}${o.label ? `<span class="lbl">${esc(o.label)}</span>` : ""}</div>
    <h1>Pay ${esc(o.venue)}</h1>
    ${amt ? `<div class="amount">${amt}</div>`
          : `<p class="lede">The amount is on your bill — you'll confirm it on the venue's payment page.</p>`}
    <a class="btn" href="/p/${esc(o.token)}/go" rel="noopener">Continue to payment</a>
    <p class="note">You'll pay on ${esc(o.venue)}'s own payment page. NUM never
    holds your money and never sees your card.</p>
    <div class="warn">Not at ${esc(o.venue)} right now? Then this code isn't for
    your table — don't pay, and tell staff.</div>
    <p class="foot">Powered by NUM · <a href="https://itsnum.com/">itsnum.com</a></p>` : `
    <div class="venue">${esc(o.venue)}${o.label ? `<span class="lbl">${esc(o.label)}</span>` : ""}</div>
    <h1>Pay by PromptPay</h1>
    ${amt ? `<div class="amount">${amt}</div>` : ""}
    <p class="lede">Open your Thai banking app and scan the <b>printed PromptPay
    QR</b> on this card — the bank pays ${esc(o.venue)} directly.</p>
    <div class="ppbox">PromptPay ID<br><span class="ppid">${esc(o.promptpayId)}</span><br>
    <span class="note">You can also enter this ID in your banking app's PromptPay
    transfer screen${amt ? ` — the amount is ${amt}` : ""}.</span></div>
    <p class="note">Payment goes straight from your bank to ${esc(o.venue)}.
    NUM never holds your money.</p>
    <div class="warn">The name your banking app shows before you confirm should
    match ${esc(o.venue)}. If it doesn't — don't pay, and tell staff.</div>
    <p class="foot">Powered by NUM · <a href="https://itsnum.com/">itsnum.com</a></p>`;
  return payShell(inner, "Pay " + o.venue + " — NUM");
}

/* ── GET /biz/pay?k= — the manager, and the print surface ────────────────── */
async function venuePayPage(req, env, url) {
  const biz = await bizAuth(env, url, req);
  if (!biz) return HTML(payShell(`<h1>That link isn't valid</h1>
    <p class="lede">Manager links rotate when a business asks for a new one.
    Check the most recent email from NUM, or reply to it and we'll reissue.</p>`, "NUM"), 401);

  const k = encodeURIComponent(url.searchParams.get("k") || "");
  const { results: links } = await env.DB.prepare(
    `SELECT l.token,l.label,l.kind,l.target,l.amount,l.currency,l.zone_type,l.state,
            (SELECT COUNT(*) FROM num_pay_events e WHERE e.token=l.token AND e.kind='scan') AS scans
       FROM num_paylinks l WHERE l.business_id=? ORDER BY l.state='revoked', l.created_at`
  ).bind(biz.id).all();
  const month = await env.DB.prepare(
    `SELECT COUNT(*) AS n FROM num_pay_events WHERE business_id=? AND kind='scan' AND day >= ?`
  ).bind(biz.id, now().slice(0, 8) + "01").first();

  const active = (links || []).filter((l) => l.state === "active");
  const retired = (links || []).filter((l) => l.state !== "active");
  const card = (l) => `
    <div class="card" data-tok="${esc(l.token)}">
      ${l.kind === "promptpay"
        ? `<img class="emv" src="/api/pay/emv/${esc(l.token)}.svg" alt="PromptPay QR ${esc(l.label)}">
           <div class="scanhint">Scan with your <b>banking app</b> to pay</div>
           <img class="numqr" src="/api/pay/qr/${esc(l.token)}.svg" alt="NUM QR ${esc(l.label)}">
           <div class="scanhint small">or camera-scan for details</div>`
        : `<img class="emv" src="/api/pay/qr/${esc(l.token)}.svg" alt="Pay QR ${esc(l.label)}">
           <div class="scanhint">Scan with your <b>camera</b> to pay</div>`}
      <div class="cardlabel">${esc(biz.name)} · ${esc(l.label)}</div>
      ${l.amount ? `<div class="cardamt">${esc(l.currency)} ${esc(l.amount)}</div>` : ""}
    </div>`;

  const row = (l) => `
    <tr class="${l.state === 'active' ? '' : 'dead'}">
      <td><b>${esc(l.label)}</b><br><span class="mut">${esc(l.kind === 'promptpay' ? 'PromptPay · ' + l.target : l.target)}</span></td>
      <td>${l.amount ? esc(l.currency + " " + l.amount) : "open"}</td>
      <td>${l.scans}</td>
      <td>${l.state === "active"
        ? `<button class="mini" onclick="setState('${esc(l.token)}','revoked')">Retire</button>`
        : `<button class="mini" onclick="setState('${esc(l.token)}','active')">Reinstate</button>`}</td>
    </tr>`;

  return HTML(`<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex"><title>Payment QRs — ${esc(biz.name)}</title>
<style>
:root{--paper:#faf8f4;--ink:#131a16;--pine:#1f3a34;--green:#1e7a4d;--line:#e0ddd4;--warn:#b4552d}
body{font:16px/1.6 -apple-system,'Segoe UI',Inter,sans-serif;background:var(--paper);color:var(--ink);
  margin:0;padding:22px 18px 60px;max-width:920px;margin-inline:auto}
h1{font-size:22px;margin:0 0 2px}
.sub{color:#4a5450;margin:0 0 18px;font-size:14px}
.nav{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 20px}
.nav a{font-size:14px;font-weight:600;text-decoration:none;padding:7px 14px;
  border-radius:10px;border:1.5px solid var(--pine);color:var(--pine)}
.nav .on{background:var(--pine);color:#fff}
.tile{background:#fff;border:1px solid var(--line);border-radius:14px;padding:18px;margin-bottom:18px}
.count{font-weight:700}
label{display:block;font-size:13px;font-weight:600;margin:10px 0 3px}
input,select{width:100%;box-sizing:border-box;font:inherit;padding:10px;border:1px solid var(--line);border-radius:9px;background:#fff}
.btn{background:var(--pine);color:#fff;border:0;border-radius:10px;padding:12px 18px;font-size:15px;font-weight:700;margin-top:12px;cursor:pointer}
.mini{font:600 13px/1 inherit;padding:6px 10px;border-radius:8px;border:1px solid var(--line);background:#fff;cursor:pointer}
table{width:100%;border-collapse:collapse;font-size:14px}
td{padding:9px 8px;border-top:1px solid var(--line);vertical-align:top}
.mut{color:#7a827e;font-size:12px;word-break:break-all}
.dead{opacity:.45}
#out{font-size:14px;margin-top:10px;color:var(--warn);white-space:pre-wrap}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:14px}
.card{background:#fff;border:1.5px solid var(--ink);border-radius:12px;padding:16px;text-align:center;page-break-inside:avoid}
.card img.emv{width:180px;height:180px}
.card img.numqr{width:74px;height:74px;margin-top:8px}
.scanhint{font-size:13px;color:#4a5450}.scanhint.small{font-size:11px}
.cardlabel{font-weight:800;margin-top:8px}
.cardamt{font-weight:700;font-size:15px}
.meter{font-size:14px;color:#4a5450}
@media print{body{padding:0;background:#fff}
  .tile,.nav,h1,.sub,#out,table,.noprint{display:none!important}
  .grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10mm;padding:8mm}}
@media (max-width:520px){.grid{grid-template-columns:1fr 1fr}}
</style></head><body>
<h1>Payment QRs</h1>
<p class="sub">${esc(biz.name)} · <span class="meter">${month?.n || 0} scans this month</span></p>
<div class="nav">
  <a href="/biz/codes?k=${k}">Codes</a>
  <a href="/biz/visitors?k=${k}">Visitors</a>
  <a href="/biz/offers?k=${k}">Offers</a>
  <a class="on" href="/biz/pay?k=${k}">Pay</a>
</div>

<div class="tile noprint">
  <b>Add a payment QR</b>
  <p class="sub" style="margin-top:4px">Guests scan it, see <i>${esc(biz.name)} · the table's name</i>,
  and pay you directly — by your own payment link, or by PromptPay from their Thai banking app.
  NUM never touches the money. Where a code pays can never be edited: retire it and make a new
  one, so a changed target is always a visible, logged act.</p>
  <label>Label</label><input id="f_label" placeholder="Table 4">
  <label>How guests pay</label>
  <select id="f_kind">
    <option value="promptpay">PromptPay (Thai banking apps)</option>
    <option value="url">My payment link (Stripe, PayPal, Square…)</option>
  </select>
  <label id="l_target">PromptPay ID — mobile, tax ID, or e-wallet</label>
  <input id="f_target" placeholder="0812345678">
  <label>Fixed amount — leave empty to let the guest enter it</label>
  <input id="f_amount" inputmode="decimal" placeholder="">
  <button class="btn" onclick="createLink()">Create</button>
  <div style="margin-top:14px;border-top:1px solid var(--line);padding-top:12px">
    <b style="font-size:14px">Whole floor at once</b>
    <p class="sub" style="margin:2px 0 8px">Uses the same payment details for every spot,
    labelled to match your table codes.</p>
    <select id="f_tpl">${Object.entries(FLOOR_TEMPLATES).map(([kk, v]) =>
      `<option value="${esc(kk)}">${esc(v.label)}</option>`).join("")}</select>
    <button class="btn" onclick="bulk()">Create floor</button>
  </div>
  <div id="out"></div>
</div>

<div class="tile noprint">
  <b>Your payment QRs</b> · <span class="count">${active.length} active</span>
  <table><tbody>${active.map(row).join("")}${retired.map(row).join("")}</tbody></table>
</div>

<div class="tile noprint"><b>Print</b>
  <p class="sub" style="margin:4px 0 0">Cmd/Ctrl-P prints just the cards below — one per spot,
  ready to cut. PromptPay cards carry the bank-app QR big and the camera QR small.</p>
</div>
<div class="grid">${active.map(card).join("")}</div>

<script>
var K=${JSON.stringify(url.searchParams.get("k") || "")};
document.getElementById('f_kind').onchange=function(){
  var pp=this.value==='promptpay';
  document.getElementById('l_target').textContent=pp?'PromptPay ID — mobile, tax ID, or e-wallet':'Payment link (https)';
  document.getElementById('f_target').placeholder=pp?'0812345678':'https://pay.example.com/yourvenue';
};
function post(p,b){return fetch(p+'?k='+encodeURIComponent(K),{method:'POST',
  headers:{'content-type':'application/json'},body:JSON.stringify(b)}).then(function(r){return r.json()})}
function say(m){document.getElementById('out').textContent=m}
function createLink(){
  post('/api/venue/pay',{label:document.getElementById('f_label').value,
    kind:document.getElementById('f_kind').value,
    target:document.getElementById('f_target').value,
    amount:document.getElementById('f_amount').value||null})
  .then(function(r){ if(r.ok) location.reload(); else say('Could not create: '+(r.hint||r.error)) })
}
function bulk(){
  post('/api/venue/pay/bulk',{template:document.getElementById('f_tpl').value,
    kind:document.getElementById('f_kind').value,
    target:document.getElementById('f_target').value,
    amount:document.getElementById('f_amount').value||null})
  .then(function(r){ if(r.ok) location.reload(); else say('Could not create: '+(r.hint||r.error)) })
}
function setState(t,s){ post('/api/venue/pay/state',{token:t,state:s})
  .then(function(r){ if(r.ok) location.reload(); else say(r.error||'failed') }) }
</script>
</body></html>`);
}
